# Generated by Django 3.2.3 on 2021-05-19 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.TextField(max_length=20, null=True, verbose_name='Sending Party')),
                ('to_id', models.TextField(max_length=20, null=True, verbose_name='Recieving Party')),
                ('message', models.TextField(max_length=500, null=True, verbose_name='Message')),
                ('projectCompleted', models.BooleanField(default=False, verbose_name='is Project completed')),
                ('artisanRead', models.BooleanField(default=False, verbose_name='artisan has Read message')),
                ('clientRead', models.BooleanField(default=False, verbose_name='client has Read message')),
                ('project_id', models.TextField(max_length=20, null=True, verbose_name='Project ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Chat Table',
            },
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField(max_length=20, null=True, verbose_name='Client ID')),
                ('artisan_id', models.TextField(max_length=20, null=True, verbose_name='Artisan ID')),
                ('fees_agreed', models.CharField(max_length=500, null=True, verbose_name='Fees Agreed')),
                ('project_id', models.TextField(max_length=500, null=True, verbose_name='Project ID')),
                ('order_id', models.TextField(max_length=500, null=True, verbose_name='Order ID')),
                ('commission', models.CharField(default=0, max_length=500, null=True, verbose_name="FIda's Commission")),
                ('dispute', models.BooleanField(default=False, verbose_name='Did Client raise dispute')),
                ('isPaid', models.BooleanField(default=False, verbose_name='Was payment made to Artisan')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Escrow_table',
            },
        ),
        migrations.CreateModel(
            name='Project_Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(max_length=20, null=True, verbose_name='Order ID')),
                ('client_id', models.TextField(max_length=20, null=True, verbose_name='Client ID')),
                ('artisan_id', models.TextField(max_length=20, null=True, verbose_name='Artisan ID')),
                ('project_title', models.TextField(max_length=500, null=True, verbose_name='Project Title')),
                ('canChat', models.BooleanField(default=False, verbose_name='Chat permission')),
                ('projectStatus', models.TextField(default='pending', max_length=15, verbose_name='Order Status')),
                ('endProject', models.BooleanField(default=False, verbose_name='Was Projected ended')),
                ('isCompleted', models.BooleanField(default=False, verbose_name='was Project completed')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Gig/Project Table',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.TextField(max_length=20, null=True, verbose_name='Sending Party')),
                ('to_id', models.TextField(max_length=20, null=True, verbose_name='Recieving Party')),
                ('transaction_type', models.TextField(max_length=20, null=True, verbose_name='Type of Transaction')),
                ('transaction_message', models.TextField(max_length=500, null=True, verbose_name='Message')),
                ('projectCompleted', models.BooleanField(default=False, verbose_name='is Project completed')),
                ('project_id', models.TextField(max_length=20, null=True, verbose_name='Project ID')),
                ('amount', models.FloatField(null=True, verbose_name='Amount Sent')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Transaction Table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=500, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=30, verbose_name='Firstname')),
                ('lastname', models.CharField(blank=True, max_length=30, verbose_name='Lastname')),
                ('user_phone', models.TextField(max_length=15, null=True, unique=True, verbose_name='Telephone number')),
                ('email', models.EmailField(max_length=90, unique=True, verbose_name='Email')),
                ('user_password', models.TextField(max_length=200, verbose_name='Password')),
                ('user_address', models.TextField(max_length=200, verbose_name='Address')),
                ('user_state', models.TextField(max_length=200, verbose_name='State')),
                ('ratings', models.IntegerField(default=1.0, max_length=200, verbose_name='Job Ratings')),
                ('role', models.TextField(default='client', max_length=50, verbose_name='User role')),
                ('walletBalance', models.FloatField(default=0.0, verbose_name='Balance')),
                ('account_name', models.TextField(default='Null', max_length=150, verbose_name='Account Name')),
                ('account_number', models.TextField(default='0000000000', max_length=150, verbose_name='Account Number')),
                ('bank_name', models.TextField(default='Null', max_length=150, verbose_name='Bank Name')),
                ('profile_complete', models.BooleanField(default=False)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False, verbose_name='Notification toggle')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Fida_user_table',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, max_length=20, verbose_name='Verification Code')),
                ('isVerified', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'Verification_table',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Ad Title')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Ad Description')),
                ('duration', models.TextField(max_length=15, null=True, verbose_name='Duration')),
                ('min_budget', models.TextField(max_length=90, verbose_name='Minimum Budget')),
                ('max_budget', models.TextField(max_length=200, verbose_name='Maximum Budget')),
                ('location', models.TextField(max_length=200, verbose_name='Location')),
                ('state', models.TextField(max_length=200, verbose_name='State')),
                ('service_fee', models.TextField(max_length=200, verbose_name='Service fee')),
                ('pitch', models.TextField(max_length=200, verbose_name='Pitch')),
                ('noOfBidders', models.IntegerField(default=0, max_length=15, verbose_name='No of Bidders')),
                ('orderStatus', models.TextField(default='pending', max_length=15, verbose_name='Order Status')),
                ('winner_id', models.CharField(max_length=500, null=True, verbose_name='Bid Winner')),
                ('winner_accept', models.BooleanField(default=False, verbose_name='Did Winner Accept Bid')),
                ('from_ads', models.BooleanField(default=False, verbose_name='Order created from ads')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'Orders_table',
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.TextField(max_length=20, null=True, verbose_name='bidders')),
                ('service_fee', models.TextField(default='10', max_length=200, verbose_name='Service fee')),
                ('pitch', models.TextField(default='hi', max_length=200, verbose_name='Pitch')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('declinedOffer', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orders')),
            ],
            options={
                'db_table': 'Bids_table',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Ad Title')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Ad Description')),
                ('duration', models.TextField(max_length=15, null=True, verbose_name='Duration')),
                ('min_budget', models.TextField(max_length=90, verbose_name='Minimum Budget')),
                ('max_budget', models.TextField(max_length=200, verbose_name='Maximum Budget')),
                ('location', models.TextField(max_length=200, verbose_name='Location')),
                ('state', models.TextField(max_length=200, verbose_name='State')),
                ('other_info', models.TextField(max_length=200, verbose_name='Other Information')),
                ('no_of_views', models.IntegerField(default=0, verbose_name='No of Views')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('artisan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'Ads_table',
            },
        ),
    ]
