# Generated by Django 2.2.13 on 2021-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ads_no_of_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='no_of_views',
            field=models.IntegerField(default=0, max_length=200, verbose_name='No of Views'),
        ),
    ]
