# Generated by Django 2.2.13 on 2021-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210509_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='no_of_views',
            field=models.IntegerField(default=0, verbose_name='No of Views'),
        ),
    ]
