# Generated by Django 3.2.3 on 2021-05-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210514_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='bidders',
            new_name='bidder',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='winner_accept',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='pitch',
            field=models.TextField(default='hi', max_length=200, verbose_name='Pitch'),
        ),
        migrations.AddField(
            model_name='bids',
            name='service_fee',
            field=models.TextField(default='10', max_length=200, verbose_name='Service fee'),
        ),
        migrations.AddField(
            model_name='orders',
            name='winner_accept',
            field=models.BooleanField(default=False, verbose_name='Did Winner Accept Bid'),
        ),
        migrations.AddField(
            model_name='orders',
            name='winner_id',
            field=models.CharField(max_length=500, null=True, verbose_name='Bid Winner'),
        ),
    ]
