# Generated by Django 3.2.3 on 2021-05-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210514_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_gig',
            name='bid_id',
        ),
        migrations.AddField(
            model_name='project_gig',
            name='order_id',
            field=models.TextField(max_length=20, null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='project_gig',
            name='projectStatus',
            field=models.TextField(default='pending', max_length=15, verbose_name='Order Status'),
        ),
    ]
