# Generated by Django 3.2.3 on 2021-05-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210515_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ratings',
            field=models.IntegerField(default=1.0, max_length=200, verbose_name='Job Ratings'),
        ),
    ]
