# Generated by Django 3.2.3 on 2021-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='order_id',
            field=models.TextField(max_length=500, null=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='isPaid',
            field=models.BooleanField(default=False, verbose_name='Was payment made to Artisan'),
        ),
    ]
