# Generated by Django 3.2.3 on 2021-05-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210517_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='commission',
            field=models.CharField(default=0, max_length=500, null=True, verbose_name="FIda's Commission"),
        ),
    ]
