# Generated by Django 3.2.3 on 2021-05-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_escrow_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='declinedOffer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='from_ads',
            field=models.BooleanField(default=False, verbose_name='Order created from ads'),
        ),
    ]
