# Generated by Django 3.2.3 on 2021-05-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210518_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Notification toggle'),
        ),
    ]
