# Generated by Django 3.2.3 on 2021-05-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='artisanRead',
            field=models.BooleanField(default=False, verbose_name='artisan has Read message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='clientRead',
            field=models.BooleanField(default=False, verbose_name='client has Read message'),
        ),
    ]
